albumentation:
  blur:
    strength: 0
    prob: 0
  clahe:
    clip_limit: [1, 1]
    tile_grid_size: [8, 8]
    prob: 0
  color_jitter:
    brightness: [1, 1]
    contrast: [1, 1]
    saturation: [1, 1]
    hue: [0, 0]
    prob: 0
  coarse_dropout:
    max_holes: 1
    max_height: 0.2
    max_width: 0.2
    min_holes: 1
    min_height: 0.1
    min_width: 0.1
    fill_value: [255, 255, 255]
    prob: 0
  downscale:
    scale_min: 1
    scale_max: 1
    prob: 0
  affine: # include: translation, rotation, scaling, shear
    scale: [0.8, 1.2]
    translate_percent: [0.1, 0.1]
    rotate: [-30, 30]
    shear: [0, 0]
    fit_output: false
    prob: 0
  fliplr: # horizontal flip
    prob: 0

