root: /content/Color_clothes
train: train
val: val

class:
        Type: ['Blazer', 'Bomber_Jacket', 'Cardigan', 'Sweater', 'Tank', 'Tee']
        Color: ['black', 'brown', 'red', 'orange', 'yellow',
                'green', 'blue', 'gray', 'white']

