weights: yolor_csp.pt
cfg: /content/drive/MyDrive/yolor/cfg/yolor_csp.cfg
data: /content/drive/MyDrive/yolor/data/data.yaml
hyp: data/hyp.scratch.640.yaml
epochs: 300
batch_size: 32
img_size:
- 448
- 448
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolor_csp
exist_ok: false
total_batch_size: 32
world_size: 1
global_rank: -1
save_dir: runs/train/yolor_csp
